### ISSUE TITLE
Server crash with NULL Merchant recipe

### ISSUE THREAD

**Issue by LemADEC** [NightKosh/Gravestone-mod-Graves#203] opened 2016-02-24 01:18 UTC
Server crash with GraveStone-2.16.0.jar

```
[20:10:26 ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@787ab3b5:
java.lang.NullPointerException
>       at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:107) ~[agn.class:?]
>       at net.minecraft.village.MerchantRecipeList.func_77202_a(SourceFile:123) ~[ago.class:?]
>       at gravestone.item.corpse.VillagerCorpseHelper.setNbt(VillagerCorpseHelper.java:76) ~[VillagerCorpseHelper.class:?]
>       at gravestone.item.corpse.CorpseHelper.getCorpse(CorpseHelper.java:91) ~[CorpseHelper.class:?]
>       at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:50) ~[GSEventsHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_390_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.30]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.30]
>       at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:313) [ForgeHooks.class:1.7.10-1614.30]
>       at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1014) [sv.class:?]
>       at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335) [yv.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
>       at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:143) [yg.class:?]
>       at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:340) [yq.class:?]
>       at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:162) [uq.class:?]
>       at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) [uj.class:?]
>       at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582) [sw.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2064) [sv.class:?]
>       at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388) [sw.class:?]
>       at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36) [yg.class:?]
>       at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:244) [yq.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1897) [sv.class:?]
>       at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213) [sw.class:?]
>       at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41) [yg.class:?]
>       at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:335) [yq.class:?]
>       at net.minecraft.world.World.func_72866_a(World.java:2678) [ahb.class:?]
>       at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:808) [mt.class:?]
>       at net.minecraft.world.World.func_72870_g(World.java:2627) [ahb.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:2427) [ahb.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637) [mt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:967) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
```

**Comment by NightKosh** [comment] 2016-03-20 19:06
Hello. I hope this bug was fixed in last commit.
But I'm not sure, cause can't reproduce it. Can you give me some tips about it? Have you got any "villagers" mods?

**Comment by LemADEC** [comment] 2016-03-20 20:29
It's part of Dizzy's Life In The Woods 2 pack. There's quite a few village changing mods like TYNKYN, Taverns, Immersive Engineering, etc. The full list is here: http://www.technicpack.net/modpack/dizzys-life-in-the-woods-2.809787/mods

**Comment by LemADEC** [comment] 2016-03-20 20:47
We've had 7 crashes over last 3 weeks.
There's no details on the entity who died in the logs.
The attacking entity is usually Zombies but can be also IE Revolver shot or Primitive Mobs Lost miner (as seen below).
I'm confused on why a lost miner would attack a villager, that doesn't sound right.
```
-- Entity being ticked --
Details:
        Entity Type: ImmersiveEngineering.revolverShot (blusunrize.immersiveengineering.common.entities.EntityRevolvershot)
        Entity ID: 84734
        Entity Name: entity.ImmersiveEngineering.revolverShot.name
        Entity's Exact location: 1.30, 65.17, -36.95
        Entity's Block location: World: (1,65,-37), Chunk: (at 1,4,11 in 0,-3; contains blocks 0,0,-48 to 15,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1,$
        Entity's Momentum: 0.27, -0.84, -0.47
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2423)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

-- Entity being ticked --
Details:
        Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
        Entity ID: 3379
        Entity Name: Zombie
        Entity's Exact location: 947.53, 41.00, 3733.13
        Entity's Block location: World: (947,41,3733), Chunk: (at 3,2,5 in 59,233; contains blocks 944,0,3728 to 959,255,3743), Region: (1,7; contains chunks 32,224 $
        Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2426)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Entity being ticked --
Details:
        Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
        Entity ID: 534532
        Entity Name: Zombie
        Entity's Exact location: -321.19, 46.00, -1026.50
        Entity's Block location: World: (-322,46,-1027), Chunk: (at 14,2,13 in -21,-65; contains blocks -336,0,-1040 to -321,255,-1025), Region: (-1,-3; contains chu$
        Entity's Momentum: 0.00, -0.08, -0.01
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2427)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Entity being ticked --
Details:
        Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
        Entity ID: 548240
        Entity Name: Zombie
        Entity's Exact location: 713.09, 19.00, 113.31
        Entity's Block location: World: (713,19,113), Chunk: (at 9,1,1 in 44,7; contains blocks 704,0,112 to 719,255,127), Region: (1,0; contains chunks 32,0 to 63,3$
        Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2427)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Entity being ticked --
Details:
        Entity Type: primitivemobs.LostMiner (net.daveyx0.primitivemobs.entity.passive.EntityLostMiner)
        Entity ID: 317226
        Entity Name: Lost Miner
        Entity's Exact location: 2463.67, 27.00, -333.59
        Entity's Block location: World: (2463,27,-334), Chunk: (at 15,1,2 in 153,-21; contains blocks 2448,0,-336 to 2463,255,-321), Region: (4,-1; contains chunks 1$
        Entity's Momentum: -0.26, -0.08, -0.03
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2445)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Entity being ticked --
Details:
        Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
        Entity ID: 448889
        Entity Name: Zombie
        Entity's Exact location: 1393.47, 37.00, 4569.30
        Entity's Block location: World: (1393,37,4569), Chunk: (at 1,2,9 in 87,285; contains blocks 1392,0,4560 to 1407,255,4575), Region: (2,8; contains chunks 64,25$
        Entity's Momentum: 0.10, -0.08, -0.06
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2445)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Entity being ticked --
Details:
        Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
        Entity ID: 588259
        Entity Name: Zombie
        Entity's Exact location: -1555.86, 26.00, 4672.58
        Entity's Block location: World: (-1556,26,4672), Chunk: (at 12,1,0 in -98,292; contains blocks -1568,0,4672 to -1553,255,4687), Region: (-4,9; contains chunks$
        Entity's Momentum: 0.03, -0.08, -0.05
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2445)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
```

**Comment by NightKosh** [comment] 2016-03-22 21:23
So I tried to reproduce this bug and catch another one in a Taverns mod - there was a villager(baker) without any recipe. This crash happened when I tried to trade with her:
java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at net.minecraft.network.PacketBuffer.func_150788_a(SourceFile:98)
	at net.minecraft.village.MerchantRecipeList.func_151391_a(SourceFile:74)
	at net.minecraft.entity.player.EntityPlayerMP.func_71030_a(EntityPlayerMP.java:725)
	at net.minecraft.entity.passive.EntityVillager.func_70085_c(EntityVillager.java:188)
	at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032)
	at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at net.minecraft.network.PacketBuffer.func_150788_a(SourceFile:98)
	at net.minecraft.village.MerchantRecipeList.func_151391_a(SourceFile:74)
	at net.minecraft.entity.player.EntityPlayerMP.func_71030_a(EntityPlayerMP.java:725)
	at net.minecraft.entity.passive.EntityVillager.func_70085_c(EntityVillager.java:188)
	at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032)
	at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@320c7001
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


And, as I assumed, I got the same bug, as you posted, when I kill this villager.

**Comment by NightKosh** [comment] 2016-03-22 21:26
But, unfortunatelly, this bug still not fixed:

`
java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:107)
	at gravestone.item.corpse.VillagerCorpseHelper.setNbt(VillagerCorpseHelper.java:71)
	at gravestone.item.corpse.CorpseHelper.getCorpse(CorpseHelper.java:91)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_391_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.village.MerchantRecipe.func_77395_g(SourceFile:107)
	at gravestone.item.corpse.VillagerCorpseHelper.setNbt(VillagerCorpseHelper.java:71)
	at gravestone.item.corpse.CorpseHelper.getCorpse(CorpseHelper.java:91)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_391_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:335)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2bd812cb
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
`

**Comment by LemADEC** [comment] 2016-03-22 21:51
I'm using a custom fixed version of Taverns, as found here: https://github.com/LemADEC/taverns . I don't remember villagers being implemented in that mod.
Nice to see you can reproduce it :)

**Comment by NightKosh** [comment] 2016-03-22 22:47
Finally it fixed.
[GraveStone-2.16.1.zip](https://github.com/NightKosh/Gravestone-mod-Graves/files/185127/GraveStone-2.16.1.zip)

**Comment by LemADEC** [comment] 2016-03-22 22:48
Thanks!

**Closed** 2016-03-22 22:47 UTC
Labels: crash
